title: My MSDS Journey
author: Ahmed Sabry
description: Completing the UT Austin MSDS program
theme: minima

# More info
email: ahmedsabry@utexas.edu
github_username: ahmedsabry-ut
repository: ahmedsabry-ut/ahmedsabry-ut.github.io
timezone: America/Toronto
linkedin_username: ahmedmsabry

# Default properties
url: "https://ahmedsabry-ut.github.io"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
permalink: pretty
future: true
show_excerpts: true
excerpt_separator: "<!--more-->"
header_pages:
  - semesters.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-relative-links
  - jekyll-gist
  - jekyll-avatar
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
